name: portfolio_backtester_env
channels:
  - conda-forge 
  - defaults
dependencies:
  - python=3.10
  - alphalens
  - boto3
  - cvxpy
  - flask
  - h5py
  - jinja2
  - matplotlib
  - numpy
  - pandas
  - pip
  - plotly
  - pytables
  - pytest
  - scikit-learn
  - seaborn
  - statsmodels
  - streamlit
  - yfinance
  - pandas_market_calendars
  - pip:
      - python-dotenv
